### ISSUE TITLE
do_sample is True,  nan appears in "eager"  mode

### ISSUE THREAD

**Issue by sunyanguomt** [VectorSpaceLab/Video-XL#14]
HI
When i run demp.py, in    attn_implementation="eager", the following problem occurs。

Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    output_ids = model.generate(input_ids, images=[video_tensor],  modalities=["video"],beacon_skip_first=beacon_skip_first,beacon_skip_last=beacon_skip_last, **gen_kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/videoxl/model/language_model/llava_qwen.py", line 1830, in generate
    return super().generate(position_ids=position_ids, attention_mask=attention_mask,inputs=inputs,beacon_skip_first=beacon_skip_first, beacon_skip_last= beacon_skip_last, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 3020, in _sample
    next_tokens = torch.multinomial(probs.to("cpu"), num_samples=1).squeeze(1).to("musa")
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

![image](https://github.com/user-attachments/assets/b5ddbb07-5826-437a-98bc-63de4d2ff6dc)

Then I found him in this position，this softmax apperas nan

![image](https://github.com/user-attachments/assets/dccd5dde-29b7-43f0-aad9-4b4aec9074d2)

This problem does not occur when using “sdpa” mode

**Comment by shuyansy** [comment]
Hi, in my implementation the model are running with "falsh-attention2" mode. It may does not work in other mode.

**Comment by shuyansy** [comment]
In my implementation, the model is running with "flash-attention" mode. It may not work in other modes

**Comment by ApolloRay** [comment]
> HI When i run demp.py, in attn_implementation="eager", the following problem occurs。
> 
> Traceback (most recent call last): File "demo.py", line 44, in output_ids = model.generate(input_ids, images=[video_tensor], modalities=["video"],beacon_skip_first=beacon_skip_first,beacon_skip_last=beacon_skip_last, **gen_kwargs) File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/opt/conda/envs/py38/lib/python3.8/site-packages/videoxl/model/language_model/llava_qwen.py", line 1830, in generate return super().generate(position_ids=position_ids, attention_mask=attention_mask,inputs=inputs,beacon_skip_first=beacon_skip_first, beacon_skip_last= beacon_skip_last, **kwargs) File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 2024, in generate result = self._sample( File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/generation/utils.py", line 3020, in _sample next_tokens = torch.multinomial(probs.to("cpu"), num_samples=1).squeeze(1).to("musa") RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
> 
> ![image](https://private-user-images.githubusercontent.com/188558853/388508960-b5ddbb07-5826-437a-98bc-63de4d2ff6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODk1NjQsIm5iZiI6MTczNDQ4OTI2NCwicGF0aCI6Ii8xODg1NTg4NTMvMzg4NTA4OTYwLWI1ZGRiYjA3LTU4MjYtNDM3YS05OGJjLTYzZGU0ZDJmZjZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwMjM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjY5MDVmMGQ5NDIxY2ZiMjQwYWUxZTEyYTY3NzlkNDdhYzFhNjlmZTE5NDViNzkwY2FjZjkyOWVhYjg4YjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FtwdRSNgY1ATXbTWkm2PfMOOYqJMtCJ6TuRwhrkeig8)
> 
> Then I found him in this position，this softmax apperas nan
> 
> ![image](https://private-user-images.githubusercontent.com/188558853/388511417-dccd5dde-29b7-43f0-aad9-4b4aec9074d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODk1NjQsIm5iZiI6MTczNDQ4OTI2NCwicGF0aCI6Ii8xODg1NTg4NTMvMzg4NTExNDE3LWRjY2Q1ZGRlLTI5YjctNDNmMC1hYWQ5LTRiNGFlYzkwNzRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwMjM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2M0YjU2ZTNiNGZjMzc1YWM1M2RhYjBhMWYxZjRhODQwYjdhOGQ1M2U2Mzk2ZDQyYTE1YmFkNDBkNzRjMTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ldcaWS6V6v2CDiojwWsmZO-IC3xcr4nKlzroeqAT_Ts)
> 
> This problem does not occur when using “sdpa” mode

where can i change the flash-implementation？
same problem

**Comment by josephyumss** [comment]
In my case, Sdpa mode also has the same issue. It seems that NaN comes up during `torch.nn.functional.scaled_dot_product_attention` and it flows to probs which causes the issue as a result.

I checked the shape of attention_mask, q, k , v but couldn't find any clues..

[llava_qwen.py] [Qwen2SdpaAttention] attention_mask.shape : torch.Size([1, 1, 14, 14])
[llava_qwen.py] [Qwen2SdpaAttention] q.shape : torch.Size([1, 28, 14, 128])
[llava_qwen.py] [Qwen2SdpaAttention] k.shape : torch.Size([1, 28, 14, 128])
[llava_qwen.py] [Qwen2SdpaAttention] v.shape : torch.Size([1, 28, 14, 128])

Also there was no "fully masked row" in the attention_mask

Is there any solution for this issue?
