### ISSUE TITLE
Environment problem.

### ISSUE THREAD

**Issue by Leon1207** [VectorSpaceLab/Video-XL#3]
Hi, thanks for your great work.

When running code eval_vnbench.py, it occurs:

```
Traceback (most recent call last):
  File "/mnt/82_store/lyd/Video-XL/eval/eval_vnbench.py", line 1, in <module>
    from videoxl.model.builder import load_pretrained_model
  File "/mnt/82_store/lyd/Video-XL/videoxl/videoxl/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/82_store/lyd/Video-XL/videoxl/videoxl/model/__init__.py", line 15, in <module>
    raise e
  File "/mnt/82_store/lyd/Video-XL/videoxl/videoxl/model/__init__.py", line 13, in <module>
    exec(f"from .language_model.{model_name} import {model_classes}")
  File "<string>", line 1, in <module>
  File "/mnt/82_store/lyd/Video-XL/videoxl/videoxl/model/language_model/llava_llama.py", line 32, in <module>
    from longva.model.llava_arch import LlavaMetaModel, LlavaMetaForCausalLM
ModuleNotFoundError: No module named 'longva'
```

**Comment by Leon1207** [comment]
> How did you resolve this issue?

Sorry I haven't solved it yet. Did you meet the same problem?

**Comment by ApolloRay** [comment]
> > How did you resolve this issue?
> 
> Sorry I haven't solved it yet. Did you meet the same problem?

same question.

**Comment by ApolloRay** [comment]
`git clone https://github.com/EvolvingLMMs-Lab/LongVA.git`
`cd LongVA/`
`python -m pip install -e "longva/.[train]"`
